proposal:
	latexmk -cd -f -pdf -pdflatex='pdflatex -interaction=batchmode'-bibtex proposal.tex
clean: 
	rm -rf proposal.pdf aux  *.bbl *.blg *.log .Z* auto *.fls *.fdb_latexmk *.synctex.gz *.out *.aux


