update:
	latexmk -cd -f -pdf -pdflatex='pdflatex -interaction=batchmode' -synctex=1 update.tex

clean: 
	rm -rf update.pdf *.aux  *.bbl *.blg *.log .Z* auto *.fls *.fdb_latexmk *.synctex.gz *.out update.pdf *.toc
